version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: arcadia_db
    environment:
      POSTGRES_DB: arcadia
      POSTGRES_USER: arcadia_user
      POSTGRES_PASSWORD: arcadia_pass
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - arcadia_network

  redis:
    image: redis:7-alpine
    container_name: arcadia_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - arcadia_network

volumes:
  postgres_data:
  redis_data:

networks:
  arcadia_network:
    driver: bridge
